#!/bin/bash
set -eu

ROOT_DIR="$(realpath $(dirname ${BASH_SOURCE[0]:-$0})/..)"

export PYTHONPATH="${ROOT_DIR}/thirdparty/pypackages/lib/python2.7/site-packages:${ROOT_DIR}/thirdparty/pypackages"
export PATH="${ROOT_DIR}/thirdparty/deps/dynamorio/build/bin64:${ROOT_DIR}/thirdparty/deps/valgrind/coregrind:${PATH}"

python ${ROOT_DIR}/fuzzer/fuzz.py $@
